name: CI-PHP8

on: [push, pull_request]

env:
  PHP_CS_IGNOR: "PHP_CS_FIXER_IGNORE_ENV=1"

jobs:

  # BetterReflection library is not yet ready for PHP8
#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Setup PHP
#        uses: shivammathur/setup-php@master
#        with:
#          php-version: 8.0
#          extensions: mbstring
#
#      - name: Get Composer Cache Directory
#        id: composer-cache
#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
#
#      - name: Cache dependencies
#        uses: actions/cache@master
#        with:
#          path: ${{ steps.composer-cache.outputs.dir }}
#          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
#          restore-keys: ${{ runner.os }}-composer-
#
#      - run: composer require phpstan/phpstan --ignore-platform-reqs && composer require phpstan/phpstan-doctrine --ignore-platform-reqs && composer require phpstan/extension-installer --ignore-platform-reqs && vendor/bin/phpstan analyse src --level max

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@master
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer require friendsofphp/php-cs-fixer --ignore-platform-reqs && PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --diff --dry-run --allow-risky=yes

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@master
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer require vimeo/psalm --ignore-platform-reqs && composer require weirdan/doctrine-psalm-plugin --ignore-platform-reqs && vendor/bin/psalm

  checks:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring
      - run: composer update --ignore-platform-reqs && vendor/bin/phpunit tests/
